## Write a Numpy program to compute the multiplication of two given matrixes

In [13]:
import numpy as np 

def mat_multiplication (A,B,op = '*'):
#     assert len(A) == len(B)

    print("original matrices are:\n")
    print(A,"\n")
    print(B,"\n")
    print("Dot multiplication \n")
    dotMult = np.dot(A,B)
    print(dotMult)

#     print("element by element multiplication")
#     C = A*B
#     print(C)

x=np.array([[1,3,6,7],[8,6,4,2]])
y=np.array([[7,6,6,8],[4,9,4,2],[8,9,6,4],[4,5,8,6]])
op = '*'
mat_multiplication(x,y,op)


#I'm not sure you want which type of multiplication broadcast or dot!

original matrices are:

[[1 3 6 7]
 [8 6 4 2]] 

[[7 6 6 8]
 [4 9 4 2]
 [8 9 6 4]
 [4 5 8 6]] 

Dot multiplication 

[[ 95 122 110  80]
 [120 148 112 104]]


## Write a NumPy program to compute the determinant of a given square array

In [18]:
import numpy as np
def mat_det (X):
    print("Your matrix determinant is: \n")
    print(x)
    y=np.linalg.det(A)
    return y

A=np.array([[7,6,6,8],[4,9,4,2],[8,9,6,4],[4,5,8,6]])
mat_det(A)

Your matrix determinant is: 

[[1 3 6 7]
 [8 6 4 2]]


624.0000000000007

## Write a NumPy program to compute the cross product of two given vectors

In [28]:
import numpy as np 

def mat_multiplication (A,B,op = 'x'):

    print("original matrices are:\n")
    print(A,"\n")
    print(B,"\n")
    print("Cross multiplication \n")
    crossMult = np.cross(A,B)
    print(crossMult)


x=[8,6,4]
y=[1,3,6]
op = 'x'
mat_multiplication(x,y,op)

original matrices are:

[8, 6, 4] 

[1, 3, 6] 

Cross multiplication 

[ 24 -44  18]


## Write a NumPy program to compute the condition number of a given matrix

In [38]:
import numpy as np
from numpy import linalg as LA

arr = np.array([[ 8, 6, 4],
   [4, 75, 7],
   [8, 0, 1]])

print("Matrix is:\n",arr)

print("Matrix Dimentions: \n",arr.ndim)

print("Matrix Data type: \n",arr.dtype)

print("Matrix Shape: \n",arr.shape)

print("MAtrix Condition Numberis: ",LA.cond(arr, np.inf))

Matrix is:
 [[ 8  6  4]
 [ 4 75  7]
 [ 8  0  1]]
Matrix Dimentions: 
 2
Matrix Data type: 
 int32
Matrix Shape: 
 (3, 3)
MAtrix Condition Numberis:  70.74193548387098


## Write a NumPy program to compute the inverse of a given matrix

In [43]:
import numpy as np
from numpy.linalg import inv

arr = np.array([[ 5, 10], [ 15, 20 ]])

print(arr,"\n")

print("inverse: \n\n",np.linalg.inv(arr))

[[ 5 10]
 [15 20]] 

inverse: 

 [[-0.4  0.2]
 [ 0.3 -0.1]]
